Vagrant.configure("2") do |config|
	config.vm.define "kbutor-bS" do |kbutor_bS|
		kbutor_bS.vm.box = "albgarci42/alpine-322"
		kbutor_bS.vm.box_version = "1"

		kbutor_bS.vm.hostname = "kbutor-bS"
		kbutor_bS.vm.network "private_network", ip: "192.168.56.110"
		config.vm.synced_folder ".", "/vagrant", type: "rsync"

		kbutor_bS.vm.provider :libvirt do |libvirt|
			libvirt.memory = 1024
			libvirt.cpus = 1
		end

		kbutor_bS.vm.provision "shell", path: "scripts/install_k3s.sh"
		kbutor_bS.vm.provision "shell", path: "scripts/deploy_app1.sh"
	end
end
