Vagrant.configure("2") do |config|
	config.vm.define "kbutor-bS" do |kbutor_bS|
		kbutor_bS.vm.box = "albgarci42/alpine-322"
		kbutor_bS.vm.box_version = "1"

		kbutor_bS.vm.hostname = "kbutor-bS"
		kbutor_bS.vm.network "private_network", ip: "192.168.56.110"
		kbutor_bS.vm.synced_folder ".", "/vagrant", disabled: true

		kbutor_bS.vm.provider :libvirt do |libvirt|
			libvirt.memory = 1024
			libvirt.cpus = 1
		end

		kbutor_bS.vm.provision "shell", path: "scripts/install_k3s.sh", args: "server"
	end
	
	config.vm.define "kbutor-bSW" do |kbutor_bSW|
		kbutor_bSW.vm.box = "albgarci42/alpine-322"
		kbutor_bSW.vm.box_version = "1"

		kbutor_bSW.vm.hostname = "kbutor-bSW"
		kbutor_bSW.vm.network "private_network", ip: "192.168.56.111"
		kbutor_bSW.vm.synced_folder ".", "/vagrant", disabled: true

		kbutor_bSW.vm.provider :libvirt do |libvirt|
			libvirt.memory = 1024
			libvirt.cpus = 1
		end

		kbutor_bSW.vm.provision "shell", path: "scripts/install_k3s.sh", args: "agent"
	end
end
